### PR TITLE
Added binary file support

### PR DESCRIPTION
**Pull request by coreagile**
Just in case one needs to work with binary files that aren't handled with optimizers.

### CODE REVIEW

**Comment by magnars** [comment]
Hi! This code looks fair enough. Could you give me an exampel use case for serving binary files through Stasis though? :)

**Comment by coreagile** [comment]
Sure! 

I’ve imagined the potential for having a site hosted using S3 and CloudFront, potentially holding a few PDF documents (white papers and such) that folks could download and read.

How does that work for an example use case?

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity

**Comment by magnars** [comment]
That makes sense. :)

I have generally served binary files (like images) and just plain static files (like css), separately from Stasis. This helps keep Stasis snappy as well. Here's an example from the Emacs Rocks! web page: https://github.com/magnars/emacsrocks.com/blob/master/src/emacs_rocks/web.clj#L68-L69

Could something like that work?

**Comment by coreagile** [comment]
Sure, but I like the simplicity of having just an export and a single s3 sync and I’m done.
Fewer moving parts.

I only use the ring form of stasis to test, while I use the export to go to production. Adding the extra complexity of an asset optimization layer when I don’t need it seems wasteful.

Does my patch make things worse? I’d think it would reduce confusion, as you can have a working system both before and after you layer in binary optimizations.

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity

**Comment by magnars** [comment]
Just trying to keep things simple. :) It seems your change isn’t very
intrusive, so let’s go for it. Would you mind adding a test to keep this
change in check?

tor. 8. aug. 2019 kl. 13:50 skrev Stephen Starkey <notifications@github.com
>:

> Sure, but I like the simplicity of having just an export and a single s3
> sync and I’m done.
> Fewer moving parts.
>
> I only use the ring form of stasis to test, while I use the export to go
> to production. Adding the extra complexity of an asset optimization layer
> when I don’t need it seems wasteful.
>
> Does my patch make things worse? I’d think it would reduce confusion, as
> you can have a working system both before and after you layer in binary
> optimizations.
>
> Stephen Starkey, ACC
> forgiveness | bravery | honesty | fairness | leadership | creativity
>
> Sent from my iPhone
>

**Comment by coreagile** [comment]
Sure thing! Thanks.

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity

**Comment by coreagile** [comment]
Done!

Also added `lein-ancient` and upgraded a few dependencies while I was in there.. hope you don't mind..

**Comment by magnars** [comment]
This looks great. Thanks for bumping the dependencies as well. I would think that lein-ancient is better suited for .lein/profiles.clj, but it's fine like this too. :)

**Comment by magnars** [comment]
Released as `[stasis "2.5.0"]`. Thanks!

**Comment by coreagile** [comment]
Wow thank you!!

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity

**Pull request merged**
